name: Build Docker image and push to registry

on:
  push:
    branches: main
    paths:
      - app/**
      - Dockerfile
  workflow_dispatch:

env:
  IMAGE_NAME: deno-app
  REGISTRY: ghcr.io

permissions:
  packages: write

jobs:
  build-and-push:
    name: Publish image to container registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set $SHA to the shortened Git commit hash
        run: echo "SHA=$(echo ${GITHUB_SHA} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Add extra labels to image
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}

      - name: Log in to ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.SHA }}
          labels: ${{ steps.meta.outputs.labels }}
